package interfaces;


import interfaces.ConsultVisJFrame;
import interfaces.ConsultMedJFrame;
import interfaces.AddRappJFrame;
import javax.swing.JTextField;
import technique.User;

/**
 *
 * @author sheitan666
 */
public class AccueilJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TestSwing
     */
    public AccueilJFrame() {
        initComponents();
        System.out.println(User.matricule);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultPrat = new javax.swing.JButton();
        btnConsultVis = new javax.swing.JButton();
        btnConsultMed = new javax.swing.JButton();
        btnAddRapport = new javax.swing.JButton();
        btnConsultRapp = new javax.swing.JButton();
        btnAddPrat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConsultPrat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultPrat.setText("Liste des praticiens");
        btnConsultPrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultPratActionPerformed(evt);
            }
        });

        btnConsultVis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultVis.setText("Liste des visiteurs");
        btnConsultVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultVisActionPerformed(evt);
            }
        });

        btnConsultMed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultMed.setText("Liste des médicaments");
        btnConsultMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultMedActionPerformed(evt);
            }
        });

        btnAddRapport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddRapport.setText("Nouveau rapport");
        btnAddRapport.setToolTipText("");
        btnAddRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRapportActionPerformed(evt);
            }
        });

        btnConsultRapp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultRapp.setText("Consulter vos rapports");
        btnConsultRapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultRappActionPerformed(evt);
            }
        });

        btnAddPrat.setText("Ajouter un praticien");
        btnAddPrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultMed, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultPrat, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultRapp, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(btnAddPrat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultVis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddRapport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultVis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultPrat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultRapp, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultMed, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPrat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(526, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultMedActionPerformed

        this.dispose();
        ConsultMedJFrame fenetreConsultMed = new ConsultMedJFrame();
        fenetreConsultMed.setVisible(true);
    }//GEN-LAST:event_btnConsultMedActionPerformed

    private void btnConsultPratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultPratActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ConsultPratJFrame fentreConsultPrat = new ConsultPratJFrame();
        fentreConsultPrat.setVisible(true);

    }//GEN-LAST:event_btnConsultPratActionPerformed

    private void btnConsultVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultVisActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ConsultVisJFrame fenetreConsultVisiteur = new ConsultVisJFrame();
        fenetreConsultVisiteur.setVisible(true);
    }//GEN-LAST:event_btnConsultVisActionPerformed

    private void btnAddRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRapportActionPerformed

        this.dispose();
        AddRappJFrame fenetreAjout = new AddRappJFrame();
        fenetreAjout.setVisible(true);

    }//GEN-LAST:event_btnAddRapportActionPerformed

    private void btnAddPratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPratActionPerformed
        this.dispose();
        AddPratJFrame fenetreAjoutPrat = new AddPratJFrame();
        fenetreAjoutPrat.setVisible(true);
    }//GEN-LAST:event_btnAddPratActionPerformed

    private void btnConsultRappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultRappActionPerformed
        // TODO add your handling code here:
        ConsultRappJFrame fentreRapports = new ConsultRappJFrame();
        this.dispose();
        fentreRapports.setVisible(true);
    }//GEN-LAST:event_btnConsultRappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilJFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrat;
    private javax.swing.JButton btnAddRapport;
    private javax.swing.JButton btnConsultMed;
    private javax.swing.JButton btnConsultPrat;
    private javax.swing.JButton btnConsultRapp;
    private javax.swing.JButton btnConsultVis;
    // End of variables declaration//GEN-END:variables
}
