package interfaces;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import metier.Praticien;
import dao.PraticienDAO;
import java.util.ArrayList;
import java.sql.SQLException;

/**
 *
 * @author sheitan666
 */
public class ConsultPratJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SeeJFrame
     */
    public ConsultPratJFrame() {
        initComponents();
        listPraticiens.removeAllItems();
        PraticienDAO praticien1 = new PraticienDAO();
        ArrayList<Praticien> listePraticiensDb = new ArrayList<>();
        listePraticiensDb = praticien1.getListePraticiens();
        int nbPraticiens = listePraticiensDb.size();

        for (int i = 0; i < nbPraticiens; i++) {
            int idPrat = listePraticiensDb.get(i).getId();
            listPraticiens.addItem(idPrat);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNom = new javax.swing.JTextField();
        inputPrenom = new javax.swing.JTextField();
        labelAdresse = new javax.swing.JLabel();
        inputAdresse = new javax.swing.JTextField();
        labelCp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inputCp = new javax.swing.JTextField();
        try {
            listPraticiens =(javax.swing.JComboBox)java.beans.Beans.instantiate(getClass().getClassLoader(), "interfaces.SeeJFrame_listEleves");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        btnHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelPrenom = new javax.swing.JLabel();
        inputVille = new javax.swing.JTextField();
        labelCp1 = new javax.swing.JLabel();
        inputStatut = new javax.swing.JTextField();
        labelAdresse1 = new javax.swing.JLabel();
        inputCoef = new javax.swing.JTextField();
        labelCp2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAdresse.setText("Adresse");

        inputAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAdresseActionPerformed(evt);
            }
        });

        labelCp.setText("Code postal");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CONSULTER UN PRATICIEN");

        inputCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCpActionPerformed(evt);
            }
        });

        listPraticiens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPraticiensActionPerformed(evt);
            }
        });

        btnHome.setText("Accueil");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Selectionnez le praticien");

        labelNom.setText("Nom de famille");

        labelPrenom.setText("Prenom");

        inputVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVilleActionPerformed(evt);
            }
        });

        labelCp1.setText("Statut du praticien");

        inputStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStatutActionPerformed(evt);
            }
        });

        labelAdresse1.setText("Ville");

        inputCoef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCoefActionPerformed(evt);
            }
        });

        labelCp2.setText("Coefficient de confiance ( noté / 10 )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(labelNom, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(labelAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(labelCp, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputAdresse, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listPraticiens, 0, 242, Short.MAX_VALUE)
                                    .addComponent(inputNom)
                                    .addComponent(inputPrenom)
                                    .addComponent(inputCp)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAdresse1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCp1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCp2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputCoef)
                                    .addComponent(inputStatut)
                                    .addComponent(inputVille, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(306, 306, 306)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listPraticiens, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputVille, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAdresse1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCp1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCp2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCoef, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAdresseActionPerformed

    private void inputCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCpActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AccueilJFrame fenetre = new AccueilJFrame();
        fenetre.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void listPraticiensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPraticiensActionPerformed

        //ON ATTEND QUE LA LISTE SOIT REMPLIE !!
        if (listPraticiens.getItemCount() < 1) {

        } else {
            String id = listPraticiens.getSelectedItem().toString();
            int idEl = Integer.parseInt(id);
            try {

                PraticienDAO praticien1 = new PraticienDAO();
                Praticien praticienFound = praticien1.getPraticienById(idEl);

                inputNom.setText(praticienFound.getNom());
                inputPrenom.setText(praticienFound.getPrenom());
                inputAdresse.setText(praticienFound.getAdresse());
                inputVille.setText(praticienFound.getVille());
                inputCoef.setText(""+praticienFound.getCoefNotoriete());
                inputStatut.setText(""+praticienFound.getStatut());
                inputCp.setText(""+praticienFound.getCodePostal());

            } catch (SQLException e1) {
                e1.printStackTrace();
            }
        }

        //on instancie un objet EleveDao et on utilise la methode getEleveById() qui retourne un objet eleve

    }//GEN-LAST:event_listPraticiensActionPerformed

    private void inputVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVilleActionPerformed

    private void inputStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStatutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStatutActionPerformed

    private void inputCoefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCoefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCoefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultPratJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultPratJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultPratJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultPratJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultPratJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JTextField inputAdresse;
    private javax.swing.JTextField inputCoef;
    private javax.swing.JTextField inputCp;
    private javax.swing.JTextField inputNom;
    private javax.swing.JTextField inputPrenom;
    private javax.swing.JTextField inputStatut;
    private javax.swing.JTextField inputVille;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAdresse;
    private javax.swing.JLabel labelAdresse1;
    private javax.swing.JLabel labelCp;
    private javax.swing.JLabel labelCp1;
    private javax.swing.JLabel labelCp2;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JComboBox<Integer> listPraticiens;
    // End of variables declaration//GEN-END:variables
}
