package interfaces;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import metier.FamilleMedoc;
import metier.Medoc;
import dao.MedocDAO;
import java.util.ArrayList;
import java.sql.SQLException;

/**
 *
 * @author sheitan666
 */
public class ConsultMedJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeleteJFrame
     */
    public ConsultMedJFrame() {
        initComponents();

        // On vide les listes préRemplies 
        listeFamilles.removeAllItems();
        listeMedocs.removeAllItems();

        MedocDAO meds = new MedocDAO();

        ArrayList<FamilleMedoc> listeFamillesDb = new ArrayList<>();
        listeFamillesDb = meds.findAllFamilles();
        int nbFamilles = listeFamillesDb.size();

        for (int i = 0; i < nbFamilles; i++) {
            String codeFamille = listeFamillesDb.get(i).getLibelle();
            listeFamilles.addItem(codeFamille);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        try {
            listeFamilles =(javax.swing.JComboBox)java.beans.Beans.instantiate(getClass().getClassLoader(), "interfaces.ConsultMedJFrame_listeFamilles");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        try {
            listeMedocs =(javax.swing.JComboBox)java.beans.Beans.instantiate(getClass().getClassLoader(), "interfaces.ConsultMedJFrame_listeMedocs");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jLabel2 = new javax.swing.JLabel();
        labelmedoc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaCompo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaEffets = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaContreIndic = new javax.swing.JTextArea();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitle.setText("CONSULTER LES MEDICAMENTS");

        listeFamilles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeFamillesActionPerformed(evt);
            }
        });

        listeMedocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeMedocsActionPerformed(evt);
            }
        });

        jLabel2.setText("Famille de médicaments");

        labelmedoc.setText("Médicament ");

        jLabel1.setText("Composition");

        textAreaCompo.setColumns(20);
        textAreaCompo.setRows(5);
        jScrollPane1.setViewportView(textAreaCompo);

        jLabel3.setText("Effets du médicament");

        textAreaEffets.setColumns(20);
        textAreaEffets.setRows(5);
        jScrollPane2.setViewportView(textAreaEffets);

        jLabel4.setText("Contre-indications à la prise de ce médicament");

        textAreaContreIndic.setColumns(20);
        textAreaContreIndic.setRows(5);
        jScrollPane3.setViewportView(textAreaContreIndic);

        btnHome.setText("Accueil");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(labelmedoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(listeMedocs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listeFamilles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addGap(168, 168, 168)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(labelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listeFamilles, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelmedoc, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(listeMedocs))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listElevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listElevesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listElevesActionPerformed

    private void listeFamillesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeFamillesActionPerformed
        // TODO add your handling code here:

        MedocDAO meds2 = new MedocDAO();
        ArrayList<Medoc> listeMedocsDb = new ArrayList<>();

        if (listeFamilles.getItemCount() < 1 || listeFamilles.getSelectedItem().toString().equals("")) {

        } else {
            listeMedocs.removeAllItems();
            //on recupere la famille choisie dans la liste déroulante (format libelle)
            String libelleFamilleMedoc = listeFamilles.getSelectedItem().toString();
            //on utilise la methode findCodeByLibelle pour recuperer le code de la famille choisie
            String codeFamille = meds2.findCodeByLibelleFamille(libelleFamilleMedoc);

            // on recupere tous les methodes ayant ce code famille 
            listeMedocsDb = meds2.findMedocsByFamily(codeFamille);
            int nbMedocs = listeMedocsDb.size();

            System.out.println(listeMedocsDb);
            for (int i = 0; i < nbMedocs; i++) {
                String nomMedoc = listeMedocsDb.get(i).getNomCommercial();
                listeMedocs.addItem(nomMedoc);
            }
        }
    }//GEN-LAST:event_listeFamillesActionPerformed

    private void listeMedocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeMedocsActionPerformed
        // TODO add your handling code here:

        MedocDAO meds2 = new MedocDAO();
        ArrayList<Medoc> listeMedocsDb = new ArrayList<>();

        if (listeMedocs.getItemCount() < 1) {

        } else {

            String medocPicked = listeMedocs.getSelectedItem().toString();

            //on utilise la methode findCodeByLibelle pour recuperer le code de la famille choisie
            Medoc medocFound = meds2.findMedocByName(medocPicked);

            textAreaEffets.setText(medocFound.getEffets());
            textAreaCompo.setText(medocFound.getComposition());
            textAreaContreIndic.setText(medocFound.getContreindic());
        }
    }//GEN-LAST:event_listeMedocsActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here
        this.dispose();
        AccueilJFrame fenetre = new AccueilJFrame();
        fenetre.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultMedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultMedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultMedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultMedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultMedJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelmedoc;
    private javax.swing.JComboBox<String> listeFamilles;
    private javax.swing.JComboBox<String> listeMedocs;
    private javax.swing.JTextArea textAreaCompo;
    private javax.swing.JTextArea textAreaContreIndic;
    private javax.swing.JTextArea textAreaEffets;
    // End of variables declaration//GEN-END:variables
}
